version: '3.5'
networks:
  basic:
    driver:
      bridge

volumes:
  db:
    driver: local

services:
  nginx:
    networks:
      - basic
    image: nginx:1.11.1-alpine
    ports:
      - "9092:80"
    volumes:
      - .:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm
  fpm:
    container_name: da_api
    networks:
      - basic
    volumes:
      - .:/var/www/html
    build:
      context: .
      dockerfile: ./docker/Dockerfile-fpm
    links:
      - db
      - redis
  db:
    networks:
      - basic
    image: postgres:14.1-alpine
    links:
      - pgadmin  
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=laravel
      - POSTGRES_DB=laravel
    volumes:
        #- "./data:/docker-entrypoint-initdb.d"
      - ./data/postgresql:/var/lib/postgresql/data
      - ./data/postgresql.conf:/etc/postgresql/postgresql.conf
  redis:
    networks:
      - basic
    image: redis:6.2.6
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  pgadmin:
    networks:
      - basic
    image: dpage/pgadmin4:latest
    ports:
      - "9093:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: delivery_agent      
      PGADMIN_DEFAULT_EMAIL: delivery_agent@dh.health
